version: '3.8'

services: 
   web:
      hostname: web.knowledgebase.docker
      container_name: knowledgebase-web
      #image: excell_app:v1
      build:
         context: ./../
         dockerfile: ./docker/web-local.dockerfile
         args:
            ENV: local
      ports:
         - "3020:8080"
      volumes:
         - "./../app/web:/app/code"
         - "./../app/web/templates:/app/templates"
         - "./../app/web/static:/app/static"
         - "./../docker/env/web-local.env:/app/code/.env"
         - "./../k6/web:/app/k6"
      networks:
         knowledge:
            ipv4_address: 172.1.0.2
      links:
         - pg
      privileged: true
#   hugo:
#      hostname: hugo.knowledgebase.docker
#      container_name: knowledgebase-hugo
#      image: klakegg/hugo:0.95.0-ext
#      command: >
#         server
#         "./src/build.sh"
#      ports:
#         - "3020:1313"
#      volumes:
#         - "./../app/hugo:/src"
#      environment:
#         - HUGO_REFRESH_TIME=3600
#         - HUGO_BASEURL=http://knowledgebase.docker
#      networks:
#         knowledge:
#            ipv4_address: 172.1.0.2
#      links:
#         - pg
#      privileged: true
   api:
      hostname: api.knowledgebase.docker
      container_name: knowledgebase-api
      #image: excell_app:v1
      build:
         context: ./../
         dockerfile: ./docker/api-local.dockerfile
         args:
            ENV: local
      ports:
         - "3021:8080"
      volumes:
         - "./../app/api:/app/code"
         - "./../docker/env/app-local.env:/app/code/.env"
         - "./../k6/api:/app/k6"
      networks:
         knowledge:
            ipv4_address: 172.1.0.4
      links:
         - pg
   pg:
      hostname: db.knowledgebase.docker
      image: 'postgres:13-alpine'
      container_name: knowledgebase-pg
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: password1
      ports:
         - "5433:5432"
      volumes:
         - "./postgres-data:/var/lib/postgresql/data"
         - "./init-scripts/postgres:/docker-entrypoint-initdb.d"
      networks:
         knowledge:
            ipv4_address: 172.1.0.3

networks:
   knowledge:
      external: false
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 172.1.0.0/16
              gateway: 172.1.0.1